receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    limit_mib: 512
    check_interval: 1s
  resource:
    attributes:
      - key: service.name
        from_attribute: service.name
        action: insert
      - key: service.version
        from_attribute: service.version
        action: insert

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "microservices"
    const_labels:
      cluster: "hacka_cluster"
      environment: "production"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [prometheus]
