# Destrói a infraestrutura de observabilidade
name: Observability Stack Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "DESTROY" to confirm'
        required: true
        type: string

jobs:
  destroy:
    if: ${{ github.event.inputs.confirm_destroy == 'DESTROY' }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ~1.5.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -var="aws_region=us-east-1" -var="environment=prod" -var="cluster_name=hacka_cluster" -auto-approve

      - name: Verify destruction
        run: |
          echo "🗑️ Infraestrutura destruída com sucesso!"
          echo "⚠️ Todos os recursos de observabilidade foram removidos."
